version: '3'

networks:
  flathunt:
    ipam:
      config:
        - subnet: 10.10.1.0/24

services:

  socks_proxy:
    image: dockage/tor-privoxy
    ports:
    - 9050:9050
    - 9051:9051
    - 8118:8118

    networks:
      flathunt:
        ipv4_address: 10.10.1.10

  proxy:
    build: ./socks-to-http-proxy
    command: -p 9999 -s  10.10.1.10:9050
    ports:
    - 9999:9999
    networks:
      flathunt: {}
  app:
    build: .
    shm_size: 512M # Workaround to fix docker crashes because of to small /dev/shm
    platform: linux/amd64 # For M1 to install google-chrome-stable; However still crashes on M1 when launching chrome (selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open window in chrome (Session info: headless chrome=109.0.5414.119))
    # command: python chrome_driver_install.py
    command: python flathunt.py
    restart: always
    ports:
    - 9222:9222
    networks:
      flathunt: {}
    environment:
      # - FLATHUNTER_TARGET_URLS=https://www.immobilienscout24.de/Suche/...;https://www.wg-gesucht.de/...
      # - FLATHUNTER_DATABASE_LOCATION=
      # - FLATHUNTER_GOOGLE_CLOUD_PROJECT_ID=
      # - FLATHUNTER_VERBOSE_LOG=
      - FLATHUNTER_LOOP_PERIOD_SECONDS=600
      # - FLATHUNTER_MESSAGE_FORMAT=
      # - FLATHUNTER_NOTIFIERS=telegram,mattermost,slack...
      # - FLATHUNTER_TELEGRAM_BOT_TOKEN=160165XXXXXXX:...
      # - FLATHUNTER_TELEGRAM_RECEIVER_IDS=12345...
      # - FLATHUNTER_MATTERMOST_WEBHOOK_URL=
      # - FLATHUNTER_SLACK_WEBHOOK_URL=
      # - FLATHUNTER_WEBSITE_SESSION_KEY=
      # - FLATHUNTER_WEBSITE_DOMAIN=
      # - FLATHUNTER_2CAPTCHA_KEY=
      # - FLATHUNTER_IMAGETYPERZ_TOKEN=
      # - FLATHUNTER_HEADLESS_BROWSER=yes
    volumes:
      - ./:/usr/src/app # not ideal, but the only way to incorporate the database (processed_ids.db), which is currently created at runtime
